//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderDetail
    {
        public PurchaseOrderDetail()
        {
            this.WarehousePartialStocks = new HashSet<WarehousePartialStock>();
        }
    
        public long ID { get; set; }
        public long PurchaseOrderID { get; set; }
        public long ProductID { get; set; }
        public bool IsPartialProduct { get; set; }
        public Nullable<long> ProductVarientID { get; set; }
        public decimal BuyRatePerUnit { get; set; }
        public int Quantity { get; set; }
    
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        public virtual ICollection<WarehousePartialStock> WarehousePartialStocks { get; set; }
    }
}
