//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        public Warehouse()
        {
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
            this.WarehouseFranchises = new HashSet<WarehouseFranchise>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public string WarehouseCode { get; set; }
        public long BusinessDetailID { get; set; }
        public string GSTNumber { get; set; }
        public string ServiceNumber { get; set; }
        public Nullable<int> ServiceLevel { get; set; }
        public long StateID { get; set; }
        public long CityID { get; set; }
        public int PincodeID { get; set; }
        public string NearbyTransport { get; set; }
        public string Measurement { get; set; }
        public string FloorSpace { get; set; }
        public string Volume { get; set; }
        public string CustomEntry { get; set; }
        public string CustomExit { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<long> ModifyBy { get; set; }
        public string NetworkIP { get; set; }
        public string DeviceType { get; set; }
        public string DeviceID { get; set; }
    
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual ICollection<WarehouseFranchise> WarehouseFranchises { get; set; }
    }
}
