//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehousePartialStock
    {
        public long ID { get; set; }
        public long PurchaseOrderDetailID { get; set; }
        public int PackUnitID { get; set; }
        public int InitialQuantity { get; set; }
        public int AvailableQuantity { get; set; }
    
        public virtual PurchaseOrderDetail PurchaseOrderDetail { get; set; }
    }
}
