//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseStock
    {
        public WarehouseStock()
        {
            this.WarehouseReturnStocks = new HashSet<WarehouseReturnStock>();
            this.WarehouseWastageStocks = new HashSet<WarehouseWastageStock>();
        }
    
        public long ID { get; set; }
        public long PurchaseOrderID { get; set; }
        public long ProductID { get; set; }
        public long ProductVarientID { get; set; }
        public Nullable<decimal> MRP { get; set; }
        public decimal BuyRatePerUnit { get; set; }
        public Nullable<decimal> SaleRatePerUnit { get; set; }
        public int InitialQuantity { get; set; }
        public int AvailableQuantity { get; set; }
        public int ReorderLevel { get; set; }
        public Nullable<bool> StockStatus { get; set; }
        public decimal PackSize { get; set; }
        public Nullable<int> PackUnitID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<long> ModifyBy { get; set; }
        public string NetworkIP { get; set; }
        public string DeviceType { get; set; }
        public string DeviceID { get; set; }
    
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        public virtual ICollection<WarehouseReturnStock> WarehouseReturnStocks { get; set; }
        public virtual ICollection<WarehouseWastageStock> WarehouseWastageStocks { get; set; }
    }
}
