//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ModelLayer.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ModelLayer.Models
{
    public partial class PurchaseOrder
    {
        public PurchaseOrder()
        {
            this.PurchaseOrderDetails = new HashSet<PurchaseOrderDetail>();
        }

        public long ID { get; set; }
        public string PurchaseOrderCode { get; set; }

        [Required(ErrorMessage = "Please select Warehouse name")]
        public long WarehouseID { get; set; }

        [Required(ErrorMessage = "Please select Supplier name")]
        public long SupplierID { get; set; }

        [Required(ErrorMessage = "Please select Order Date")]
        public System.DateTime OrderDate { get; set; }

        [Required(ErrorMessage = "Please Select Expected Delivery Date")]
        public System.DateTime ExpetedDeliveryDate { get; set; }
        public decimal Amount { get; set; }
        public Boolean IsSent { get; set; }
        public int IsAcceptedBySupplier { get; set; }
        public Nullable<long> AcceptedByID { get; set; }
        public string SupplierRemark { get; set; }
        public Nullable<DateTime> DeliveryDate { get; set; }
        public string Remark { get; set; }
        public Boolean IsActive { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<long> ModifyBy { get; set; }
        public string NetworkIP { get; set; }
        public string DeviceType { get; set; }
        public string DeviceID { get; set; }
        public long? DVId { get; set; }
        public long? FVId { get; set; }
        public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        public virtual PersonalDetail PersonalDetails { get; set; }
    }
}
