//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLayer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class PurchaseOrderDetail
    {           
        public long ID { get; set; }
        public long PurchaseOrderID { get; set; }
        
        public long ProductID { get; set; }
        public string ProductNickname { get; set; }     
        public Nullable<long> ProductVarientID { get; set; }       
        public int Quantity { get; set; }     
        public decimal UnitPrice { get; set; }
        public string Remark { get; set; }
        public Nullable<long> RateCalculationId { get; set; }
        public Boolean IsActive { get; set; }  
        public long? RateMatrixId { get; set; }
        public long? RateMatrixExtensionId { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}
