//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ModelLayer.Models
{    
    public partial class Supplier
    {
        public Supplier()
        {
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
            //this.States = new HashSet<State>();
            //this.Cities=new HashSet<City>();
            //this.Pincodes = new HashSet<Pincode>();
        }
    
        public long ID { get; set; }

        [Required(ErrorMessage = "Please Enter Supplier Name")]        
        public string Name { get; set; }
        public string SupplierCode { get; set; }
        public string ContactPerson { get; set; }
        public string Address { get; set; }

        [Required(ErrorMessage = "Please Enter Mobile Numbrer")] 
        public string Mobile { get; set; }
        public string Landline { get; set; }

        [Required(ErrorMessage = "Please Enter Email")]       
        public string Email { get; set; }
        public long? PaymentInTermsID { get; set; }   ///Added by Priti
        public string FAX { get; set; }
        public string GSTNumber { get; set; }
        public string PAN { get; set; }
        public string Website { get; set; }
        public string CC { get; set; }
        public long StateID { get; set; }
        public long CityID { get; set; }

         [Required(ErrorMessage = "Please Enter Pincode")]      
        public int PincodeID { get; set; }
        public Nullable<long> WarehouseID { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<long> ModifyBy { get; set; }
        public string NetworkIP { get; set; }
        public string DeviceType { get; set; }
        public string DeviceID { get; set; }
        public string FSSILicenseNo { get; set; }  ///Added by Priti
        public string InsecticidesLicenseNo { get; set; }    ///Added by Priti
            [NotMapped]
            public string CityName { get; set; } ///Added by Priti on 13-2-2019
        [NotMapped]
        public string StateName { get; set; }///Added by Priti on 13-2-2019
        public virtual PersonalDetail PersonalDetails{get;set;}    
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
        //public virtual ICollection<State> States { get; set; }
        //public virtual ICollection<City> Cities{get;set;}
        //public virtual ICollection<Pincode> Pincodes{get;set;}
    }
}
