//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseFranchise
    {
        public long ID { get; set; }
        public long WarehouseID { get; set; }
        public int FranchiseID { get; set; }
        public Boolean IsActive { get; set; }
    
        public virtual Warehouse Warehouse { get; set; }
    }
}
